all: sum.zip fastfib.zip sum2.zip strxxx.zip

sum.zip: ./sum/*.c
	rm -fr ./$@
	zip $@ ./sum/*.c

fastfib.zip: ./fastfib/*.c
	rm -fr ./$@
	zip $@ ./fastfib/*.c

sum2.zip: ./sum2/*.c
	rm -fr ./$@
	zip $@ ./sum2/*.c

strxxx.zip: ./strxxx/*.c
	rm -fr ./$@
	zip $@ ./strxxx/*.c
